version: '3.8'

services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdb
    networks:
      - influxdb-telegraf-net
    volumes:
      - ${INFLUXDB_DATA_DIR}:/var/lib/influxdb2
    expose:
      - "8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: unless-stopped

  telegraf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TELEGRAF_VERSION: ${TELEGRAF_VERSION} 
    container_name: telegraf
    networks:
      - influxdb-telegraf-net
    volumes:
      - ${TELEGRAF_CONFIG_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./scripts/cisco:/scripts:ro
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      - influxdb-telegraf-net
    ports:
      - "8087:8087"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

networks:
  influxdb-telegraf-net:
    driver: bridge
