version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - portainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_DIR:-/opt/portainer/data}:/data
    ports:
      - "9000:9000"
      - "9443:9443"  # HTTPS Port
    environment:
      - TZ=${TZ:-UTC}
    restart: unless-stopped

networks:
  portainer-net:
    driver: bridge