# Grafana Datasources Configuration
apiVersion: 1

datasources:
  # InfluxDB 2.x Datasource
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: 
      defaultBucket: 
      tlsSkipVerify: true
    secureJsonData:
      token: 
    isDefault: true
    editable: false

  # Prometheus Datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
    isDefault: false
    editable: false

  # InfluxQL for legacy queries (optional)
  - name: InfluxDB-QL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: InfluxQL
      httpMode: POST
      organization: 
      defaultBucket: 
    secureJsonData:
      token: 
    isDefault: false
    editable: false