version: '3.8'

services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION:-2.7.0}
    container_name: ${INFLUXDB_CONTAINER_NAME}
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ${INFLUXDB_DATA_DIR}:/var/lib/influxdb2
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: unless-stopped

  telegraf:
    image: telegraf-snmp:${TELEGRAF_VERSION:-1.25.0}
    container_name: ${TELEGRAF_CONTAINER_NAME}
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ${TELEGRAF_CONFIG_FILE}:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    restart: unless-stopped


networks:
  ${NETWORK_NAME}:
    driver: bridge
